// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEGPUVUzUU2SfTffbjTYKaaGsYe8qFKJc',
    appId: '1:800060505803:web:b7a1833996267e3601254e',
    messagingSenderId: '800060505803',
    projectId: 'angela-yu-c91da',
    authDomain: 'angela-yu-c91da.firebaseapp.com',
    storageBucket: 'angela-yu-c91da.appspot.com',
    measurementId: 'G-HRE63Y7QVF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7zg40X8QdpwMmQcUx8xTh_LMadUVfrv4',
    appId: '1:800060505803:android:9889d60e5ef5f0f501254e',
    messagingSenderId: '800060505803',
    projectId: 'angela-yu-c91da',
    storageBucket: 'angela-yu-c91da.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTGqRDVyu579m8aXZTbBDaVw0ezX_jhUc',
    appId: '1:800060505803:ios:1ed3608e303535b801254e',
    messagingSenderId: '800060505803',
    projectId: 'angela-yu-c91da',
    storageBucket: 'angela-yu-c91da.appspot.com',
    iosBundleId: 'com.example.angelaYu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTGqRDVyu579m8aXZTbBDaVw0ezX_jhUc',
    appId: '1:800060505803:ios:1ed3608e303535b801254e',
    messagingSenderId: '800060505803',
    projectId: 'angela-yu-c91da',
    storageBucket: 'angela-yu-c91da.appspot.com',
    iosBundleId: 'com.example.angelaYu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEGPUVUzUU2SfTffbjTYKaaGsYe8qFKJc',
    appId: '1:800060505803:web:6b6f9fef61eafb6b01254e',
    messagingSenderId: '800060505803',
    projectId: 'angela-yu-c91da',
    authDomain: 'angela-yu-c91da.firebaseapp.com',
    storageBucket: 'angela-yu-c91da.appspot.com',
    measurementId: 'G-83CE7YKKB0',
  );
}
